Style/DotPosition:
  EnforcedStyle: trailing

Metrics/LineLength:
  Max: 120

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/EmptyLinesAroundBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false
