version: '2'

services:
  mongo-dev:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db
  mongo-test:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-test-data:/data/db
  mongo-client:
    image: mongo
    command: mongo --host=mongo-dev
    links:
      - mongo-dev:mongo-dev

volumes:
  mongo-dev-data:
    driver: local
  mongo-test-data:
    driver: local
